### ISSUE TITLE
Glitch/incompatilble with module Symmetrics_Trustedrating

### ISSUE THREAD

**Issue by riker09** [avstudnitz/AvS_ScopeHint#21]
I stumbled across a minor glitch/incompatibility with the module Symmetrics_Trustedrating. This module adds some config fields for TrustedShops in the backend configuration, but somehow the config paths are messed up. The module comes with three fields, defined in modules' `system.xml`:

```
trustedrating/data/trustedrating_id
trustedrating/data/trustbadge_code_snippet
trustedrating/data/review_sticker_code_snippet
```

But the path for the second field `trustbadge_code_snippet` in the backend is rendered as `trustedrating/trustbadge/code_snippet`. The `data` element has gone missing. Instead `trustbadge` is being displayed. My only guess would be that there is some problem with the naming convention here. `data` seems a little bit too generic and the ScopeHint module might have a problem with this. Unfortunately I don't have the time to dig into this further.

Here's a screenshot of the error:

![ts](https://cloud.githubusercontent.com/assets/568497/13394235/630f6098-dee7-11e5-9ce6-6c9a244dbcb4.png)

**Comment by paales** [comment]
@riker09 I know it is possible to give a custom `config_path` for each config. Do you perhaps have a copy of the system.xml? 

Can't find the exact config, but they do use the custom `config_path`:
https://github.com/symmetrics/trustedshops_trustedrating/blob/master/build/app/code/community/Symmetrics/TrustedRating/etc/system.xml#L170

**Comment by riker09** [comment]
@paales Wow, I wasn't aware that this is possible. This is exactly what was causing the issue. Nothing wrong with this module, then. I'm closing this issue and I think I learned something today. ;)
