### ISSUE TITLE
What about Magento 2

### ISSUE THREAD

**Issue by herveguetin** [avstudnitz/AvS_ScopeHint#23]
Hey there - this extension is an every-day life saver on Magento 1.
So you guessed it: any plan to make it available fo Magento 2?

**Comment by paales** [comment]
A quick Google search gives the following repository:
https://github.com/ericthehacker/magento2-configscopehints

I haven't tested the module, but it's worth checking out.

**Comment by avstudnitz** [comment]
I have started work at https://github.com/avstudnitz/AvS_ScopeHint2. It supports warning when a config value is overwritten, and prints the config path. Everything else (products, categories) isn't done yet, I don't have any plans with that at the moment.
