### ISSUE TITLE
Unable to edit product in admin panel

### ISSUE THREAD

**Issue by LordHansolo** [avstudnitz/AvS_ScopeHint#30]
### Preconditions
1. Magento 2.2.7

### Steps to reproduce
1. Create\Edit product with tier prices.

### Expected result
1. Possibility to edit product with tier prices.

### Actual result
1. Error occurs during edit product with tier prices.

Exception #0 (Exception): Notice: Array to string conversion in /var/www/html/test/vendor/avstudnitz/scopehint2/Plugin/ProductEavDataProviderPlugin.php on line 76

### Additional Information
$value on line 76 class ProductEavDataProviderPlugin.php for tier prices is array.

**Comment by avstudnitz** [comment]
Could you re-create this issue in https://github.com/avstudnitz/AvS_ScopeHint2/? This module is compatible to Magento 1 only.

**Comment by LordHansolo** [comment]
Ups, sorry.

Anyway I can see that issue report exist for Magento 2 https://github.com/avstudnitz/AvS_ScopeHint2/issues/13
